### PR TITLE
fix image name comparison and keep container id

### PR DESCRIPTION
**Pull request by yteraoka**
ImageName from cluster does not container repository path.
But, name from container registry contains path.
So, adjust these format.

Add support that image spacified in container id (digest begining with `sha256:`) in kubernetes manifest.

### CODE REVIEW

**Comment by marekaf** [comment]
Hi and thanks for the PR:) 

would you mind fixing this go lint issue:
```
./internal/worker/filter.go:68:4: var containerId should be containerID
Found 1 lint suggestions; failing.
make: *** [lint] Error 1
```

thanks! 

I'll setup up github actions to report better is lint & tests are passing.

**Comment by marekaf** [comment]
oh and it's failing the unit test `TestExistsInCluster`

**Comment by yteraoka** [comment]
> oh and it's failing the unit test `TestExistsInCluster`

I fixed test data.

**Comment by yteraoka** [comment]
> would you mind fixing this go lint issue:
> 
> ```
> ./internal/worker/filter.go:68:4: var containerId should be containerID
> Found 1 lint suggestions; failing.
> make: *** [lint] Error 1
> ```

I fixed this lint error.

**Review by marekaf — APPROVED** [review]
lgtm

**Pull request merged**
